use serde::Deserialize;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use crate::color::{cyan, dim, green};
use crate::typechecker;

/// Parsed project.toml configuration.
#[derive(Debug, Deserialize, Default)]
pub struct ProjectConfig {
    #[serde(default)]
    pub project: ProjectSection,
    #[serde(default)]
    pub library: Option<LibrarySection>,
    #[serde(default)]
    pub bin: Option<BinSection>,
    #[serde(default)]
    pub deps: Option<HashMap<String, DepEntry>>,
    #[serde(default)]
    pub formatter: FormatterSection,
}

#[derive(Debug, Deserialize, Default)]
#[allow(dead_code)]
pub struct ProjectSection {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub tests_dir: Option<String>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct FormatterSection {
    #[serde(default = "FormatterSection::default_width")]
    pub width: usize,
}

impl Default for FormatterSection {
    fn default() -> Self {
        FormatterSection {
            width: Self::default_width(),
        }
    }
}

impl FormatterSection {
    fn default_width() -> usize {
        crate::formatter::DEFAULT_WIDTH
    }
}

#[derive(Debug, Deserialize, Clone)]
pub struct LibrarySection {
    pub module: String,
    pub expose: Vec<String>,
}

#[derive(Debug, Deserialize, Clone, Default)]
pub struct BinSection {
    #[serde(default)]
    pub main: Option<String>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct DepEntry {
    /// Local path dependency.
    #[serde(default)]
    pub path: Option<String>,
    /// Git repository URL.
    #[serde(default)]
    pub git: Option<String>,
    /// Git tag to checkout.
    #[serde(default)]
    pub tag: Option<String>,
    /// Git branch to checkout.
    #[serde(default)]
    pub branch: Option<String>,
    /// Exact git commit hash to checkout.
    #[serde(default)]
    pub rev: Option<String>,
    /// Module name alias for the dependency.
    #[serde(rename = "as")]
    pub alias: Option<String>,
    /// Version requirement for Hex dependencies.
    #[serde(default)]
    pub version: Option<String>,
}

impl DepEntry {
    /// Whether this is a Hex dependency (no path or git specified).
    pub fn is_hex(&self) -> bool {
        self.path.is_none() && self.git.is_none()
    }
}

/// Resolved lockfile entry for a dependency.
#[derive(Debug, Deserialize, serde::Serialize, Clone)]
pub struct LockEntry {
    // Git fields
    #[serde(skip_serializing_if = "Option::is_none")]
    pub git: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub commit: Option<String>,
    // Hex fields
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hex: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
}

impl LockEntry {
    pub fn new_git(git: String, r#ref: Option<String>, commit: String) -> Self {
        LockEntry {
            git: Some(git),
            r#ref,
            commit: Some(commit),
            hex: None,
            version: None,
            checksum: None,
        }
    }

    pub fn new_hex(name: String, version: String, checksum: String) -> Self {
        LockEntry {
            git: None,
            r#ref: None,
            commit: None,
            hex: Some(name),
            version: Some(version),
            checksum: Some(checksum),
        }
    }

    pub fn is_hex(&self) -> bool {
        self.hex.is_some()
    }
}

/// Parsed saga.lock file.
#[derive(Debug, Deserialize, serde::Serialize, Default)]
pub struct Lockfile {
    #[serde(default)]
    pub deps: HashMap<String, LockEntry>,
}

impl Lockfile {
    pub fn load(project_root: &Path) -> Option<Self> {
        let path = project_root.join("saga.lock");
        let contents = std::fs::read_to_string(&path).ok()?;
        toml::from_str(&contents).ok()
    }

    pub fn save(&self, project_root: &Path) -> Result<(), String> {
        let path = project_root.join("saga.lock");
        let contents = toml::to_string_pretty(self)
            .map_err(|e| format!("failed to serialize lockfile: {}", e))?;
        let header = "# This file is auto-generated by saga. Do not edit.\n\n";
        std::fs::write(&path, format!("{}{}", header, contents))
            .map_err(|e| format!("failed to write saga.lock: {}", e))
    }
}

impl ProjectConfig {
    pub fn load(project_root: &Path) -> Self {
        let path = project_root.join("project.toml");
        match std::fs::read_to_string(&path) {
            Ok(contents) => toml::from_str(&contents).unwrap_or_else(|e| {
                eprintln!("Warning: failed to parse project.toml: {}", e);
                ProjectConfig::default()
            }),
            Err(_) => ProjectConfig::default(),
        }
    }

    pub fn tests_dir(&self) -> &str {
        self.project.tests_dir.as_deref().unwrap_or("tests")
    }

    /// The main entry point file. Defaults to "src/Main.saga".
    pub fn main_file(&self) -> &str {
        self.bin
            .as_ref()
            .and_then(|b| b.main.as_deref())
            .unwrap_or("src/Main.saga")
    }

    /// Whether this project can be run (has a binary entry point).
    pub fn is_bin(&self) -> bool {
        // Backward compat: if no [library] or [bin] section, treat as bin
        if self.library.is_none() && self.bin.is_none() {
            return true;
        }
        self.bin.is_some()
    }

    /// Whether this project is a library.
    #[allow(dead_code)]
    pub fn is_library(&self) -> bool {
        self.library.is_some()
    }

    /// Validate the config, returning errors if any.
    pub fn validate(&self) -> Result<(), String> {
        if let Some(lib) = &self.library {
            for exposed in &lib.expose {
                if exposed != &lib.module && !exposed.starts_with(&format!("{}.", lib.module)) {
                    return Err(format!(
                        "exposed module '{}' must be prefixed by library module '{}'",
                        exposed, lib.module
                    ));
                }
            }
        }

        if let Some(deps) = &self.deps {
            for (name, dep) in deps {
                let source_count = [dep.path.is_some(), dep.git.is_some()]
                    .iter()
                    .filter(|&&b| b)
                    .count();
                if source_count > 1 {
                    return Err(format!(
                        "dependency '{}' cannot have both 'path' and 'git'",
                        name
                    ));
                }
                if dep.is_hex() {
                    // Hex dep: version is required
                    if dep.version.is_none() {
                        return Err(format!(
                            "dependency '{}' must have 'version' (Hex dep), or specify 'path' or 'git'",
                            name
                        ));
                    }
                }
                if let Some(path) = &dep.path {
                    let dep_path = Path::new(path);
                    if !dep_path.exists() {
                        return Err(format!(
                            "dependency '{}' path '{}' does not exist",
                            name, path
                        ));
                    }
                    if !dep_path.join("project.toml").exists() {
                        return Err(format!(
                            "dependency '{}' at '{}' has no project.toml",
                            name, path
                        ));
                    }
                }
                if dep.git.is_some() {
                    let ref_count = [&dep.tag, &dep.branch, &dep.rev]
                        .iter()
                        .filter(|r| r.is_some())
                        .count();
                    if ref_count > 1 {
                        return Err(format!(
                            "dependency '{}' can only specify one of 'tag', 'branch', or 'rev'",
                            name
                        ));
                    }
                }
            }
        }

        Ok(())
    }
}

// --- Git dependency caching ---

/// Get the global cache directory for git dependencies.
fn cache_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".saga").join("cache").join("git")
}

/// Hash a git URL to a short directory name.
fn url_hash(url: &str) -> String {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    url.hash(&mut hasher);
    let hash = hasher.finish();
    let name = url
        .trim_end_matches('/')
        .rsplit('/')
        .next()
        .unwrap_or("dep")
        .trim_end_matches(".git");
    format!("{}-{:016x}", name, hash)
}

/// Ensure a bare clone of the repo exists in the cache. Returns the path to the bare repo.
/// If `needed_commit` is provided and already exists in the repo, skip fetching.
fn ensure_bare_clone(url: &str, needed_commit: Option<&str>) -> Result<PathBuf, String> {
    let dir = cache_dir().join(url_hash(url));
    let repo_dir = dir.join("repo");

    if repo_dir.exists() {
        // If we already have the commit we need, skip the network fetch
        if let Some(commit) = needed_commit {
            let output = std::process::Command::new("git")
                .args(["cat-file", "-t", commit])
                .current_dir(&repo_dir)
                .output()
                .map_err(|e| format!("failed to run git cat-file: {}", e))?;
            if output.status.success() {
                return Ok(repo_dir);
            }
        }

        // Older versions of saga used `git clone --bare` (without --mirror), which
        // doesn't configure a fetch refspec. In that case `git fetch` is a no-op
        // and the bare cache stays frozen at clone time. Repair such caches by
        // setting the mirror refspec before fetching.
        let _ = std::process::Command::new("git")
            .args([
                "config",
                "remote.origin.fetch",
                "+refs/heads/*:refs/heads/*",
            ])
            .current_dir(&repo_dir)
            .status();

        let status = std::process::Command::new("git")
            .args(["fetch", "--all", "--tags", "--quiet"])
            .current_dir(&repo_dir)
            .status()
            .map_err(|e| format!("failed to run git fetch: {}", e))?;
        if !status.success() {
            return Err(format!("git fetch failed for {}", url));
        }
    } else {
        std::fs::create_dir_all(&dir).map_err(|e| format!("failed to create cache dir: {}", e))?;
        // Use --mirror so the cache stays in sync with the remote on subsequent
        // fetches. (`--bare` alone doesn't set up a fetch refspec, so `git fetch`
        // would never update refs/heads/*.)
        let status = std::process::Command::new("git")
            .args(["clone", "--mirror", "--quiet", url])
            .arg(&repo_dir)
            .status()
            .map_err(|e| format!("failed to run git clone: {}", e))?;
        if !status.success() {
            return Err(format!("git clone failed for {}", url));
        }
    }

    Ok(repo_dir)
}

/// Resolve a git ref (tag, branch, or rev) to a concrete commit hash.
fn resolve_ref(bare_repo: &Path, dep: &DepEntry) -> Result<String, String> {
    let ref_spec = if let Some(tag) = &dep.tag {
        format!("refs/tags/{}", tag)
    } else if let Some(branch) = &dep.branch {
        format!("refs/heads/{}", branch)
    } else if let Some(rev) = &dep.rev {
        rev.clone()
    } else {
        "HEAD".to_string()
    };

    let output = std::process::Command::new("git")
        .args(["rev-parse", &ref_spec])
        .current_dir(bare_repo)
        .output()
        .map_err(|e| format!("failed to run git rev-parse: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "failed to resolve ref '{}': {}",
            ref_spec,
            stderr.trim()
        ));
    }

    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

/// Ensure a working copy at a specific commit exists. Returns the checkout path
/// and whether an existing checkout was reused as-is (true means we did nothing
/// — caller can skip recompilation).
fn ensure_checkout(
    bare_repo: &Path,
    commit: &str,
    target_dir: &Path,
) -> Result<(PathBuf, bool), String> {
    if target_dir.exists() {
        // Check whether the existing checkout is already at the requested commit.
        let output = std::process::Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(target_dir)
            .output()
            .map_err(|e| format!("failed to run git rev-parse: {}", e))?;
        if output.status.success() {
            let current = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if current == commit {
                return Ok((target_dir.to_path_buf(), true));
            }
        }

        // Stale checkout (different commit, or not a git dir). Wipe and re-clone
        // so any compiled artifacts (ebin/, priv/) are regenerated as well.
        std::fs::remove_dir_all(target_dir)
            .map_err(|e| format!("failed to remove stale checkout: {}", e))?;
    }

    std::fs::create_dir_all(target_dir)
        .map_err(|e| format!("failed to create checkout dir: {}", e))?;

    let status = std::process::Command::new("git")
        .args(["clone", "--quiet"])
        .arg(bare_repo)
        .arg(target_dir)
        .status()
        .map_err(|e| format!("failed to clone from cache: {}", e))?;
    if !status.success() {
        let _ = std::fs::remove_dir_all(target_dir);
        return Err("git clone from cache failed".to_string());
    }

    let status = std::process::Command::new("git")
        .args(["checkout", "--quiet", commit])
        .current_dir(target_dir)
        .status()
        .map_err(|e| format!("failed to checkout {}: {}", commit, e))?;
    if !status.success() {
        let _ = std::fs::remove_dir_all(target_dir);
        return Err(format!("git checkout failed for commit {}", commit));
    }

    Ok((target_dir.to_path_buf(), false))
}

/// Resolve a git dependency: fetch into global bare cache, checkout into project-local _build/deps/.
/// Returns (checkout_path, resolved_commit, reused) where `reused` is true if the
/// existing checkout was already at the requested commit.
pub fn resolve_git_dep(
    dep_name: &str,
    dep: &DepEntry,
    locked_commit: Option<&str>,
    target_dir: &Path,
) -> Result<(PathBuf, String, bool), String> {
    let url = dep
        .git
        .as_ref()
        .ok_or_else(|| format!("dependency '{}' has no git URL", dep_name))?;

    let bare_repo = ensure_bare_clone(url, locked_commit)?;

    let commit = if let Some(locked) = locked_commit {
        locked.to_string()
    } else {
        resolve_ref(&bare_repo, dep)?
    };

    let (checkout, reused) = ensure_checkout(&bare_repo, &commit, target_dir)?;

    Ok((checkout, commit, reused))
}

// --- Resolve a dep entry to a local directory path ---

/// Resolve a single dependency to a local filesystem path.
/// - Path deps: joined with `config_dir` (the directory of the project.toml
///   that declared the dep — path deps are relative to that file).
/// - Git deps: always live flat under `top_project_root/deps/{name}`,
///   regardless of which transitive config declared them.
fn resolve_dep_to_path(
    dep_name: &str,
    dep_entry: &DepEntry,
    config_dir: &Path,
    top_project_root: &Path,
    lockfile: Option<&Lockfile>,
) -> Result<PathBuf, String> {
    if let Some(path) = &dep_entry.path {
        let p = config_dir.join(path);
        p.canonicalize()
            .map_err(|e| format!("dependency '{}' path '{}': {}", dep_name, path, e))
    } else if dep_entry.git.is_some() {
        let locked_commit = lockfile
            .and_then(|lf| lf.deps.get(dep_name))
            .and_then(|entry| entry.commit.as_deref());

        if locked_commit.is_none() {
            return Err(format!(
                "git dependency '{}' is not installed. Run `saga install` first.",
                dep_name
            ));
        }

        // Git deps are checked out into <top_project_root>/deps/{name}
        let target = crate::hex::package_dir(top_project_root, dep_name);
        if !target.exists() {
            return Err(format!(
                "git dependency '{}' is not installed. Run `saga install` first.",
                dep_name
            ));
        }
        Ok(target)
    } else {
        Err(format!("dependency '{}' has no 'path' or 'git'", dep_name))
    }
}

// --- Install (fetch + lockfile) ---

/// Recursively fetch all deps (git and Hex) and collect lock entries.
///
/// All deps (direct + transitive) are installed flat under
/// `top_project_root/deps/`. `config_dir` is the directory of the current
/// project.toml being processed — it differs from `top_project_root` once we
/// recurse into a transitive dep's own project.toml.
fn install_deps_recursive(
    top_project_root: &Path,
    config_dir: &Path,
    lockfile: &mut Lockfile,
    installing: &mut HashSet<String>,
    depth: usize,
) -> Result<(), String> {
    let config = ProjectConfig::load(config_dir);

    let deps = match &config.deps {
        Some(deps) => deps.clone(),
        None => return Ok(()),
    };

    let indent = "  ".repeat(depth + 1);

    for (dep_name, dep_entry) in &deps {
        if dep_entry.is_hex() {
            install_hex_dep_recursive(
                top_project_root,
                dep_name,
                dep_entry,
                lockfile,
                installing,
                &indent,
                depth,
            )?;
            continue;
        }

        // Cycle detection for git/path deps
        let dep_key = if let Some(url) = &dep_entry.git {
            url.clone()
        } else if let Some(path) = &dep_entry.path {
            config_dir
                .join(path)
                .canonicalize()
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_else(|_| path.clone())
        } else {
            continue;
        };

        if !installing.insert(dep_key.clone()) {
            return Err(format!(
                "circular dependency detected: '{}' depends on itself (directly or transitively)",
                dep_name
            ));
        }

        let (dep_path, reused) = if let Some(url) = &dep_entry.git {
            let ref_label = dep_entry
                .tag
                .as_deref()
                .or(dep_entry.branch.as_deref())
                .or(dep_entry.rev.as_deref())
                .unwrap_or("HEAD");

            eprintln!(
                "{}{} {} ({} @ {})...",
                indent,
                dim("Fetching"),
                dep_name,
                url,
                ref_label
            );

            let target_dir = crate::hex::package_dir(top_project_root, dep_name);
            let (checkout_path, commit, reused) =
                resolve_git_dep(dep_name, dep_entry, None, &target_dir)?;

            let dep_config = ProjectConfig::load(&checkout_path);
            if dep_config.library.is_none() {
                return Err(format!(
                    "git dependency '{}' has no [library] section in project.toml",
                    dep_name
                ));
            }

            let short_commit = &commit[..commit.len().min(12)];
            let label = if reused { "Up to date" } else { "Resolved" };
            eprintln!("{}{} {} -> {}", indent, cyan(label), dep_name, short_commit);

            lockfile.deps.insert(
                dep_name.clone(),
                LockEntry::new_git(
                    url.clone(),
                    dep_entry.tag.clone().or(dep_entry.branch.clone()),
                    commit,
                ),
            );

            (checkout_path, reused)
        } else if let Some(path) = &dep_entry.path {
            // Path deps are relative to the config file that declared them.
            let p = config_dir.join(path);
            let canonical = p
                .canonicalize()
                .map_err(|e| format!("dependency '{}' path '{}': {}", dep_name, path, e))?;
            // Path deps are user-editable — never assume they're unchanged.
            (canonical, false)
        } else {
            continue;
        };

        // Compile Erlang sources, unless the checkout is unchanged AND already
        // built. Build tool selection: erlang.mk > rebar3 > erlc.
        let already_built = reused && crate::hex::is_compiled(top_project_root, dep_name);
        if already_built {
            eprintln!("{}{} {} (already built)", indent, dim("Skipping"), dep_name);
        } else if dep_path.join("erlang.mk").exists() {
            eprintln!("{}{} {} (erlang.mk)...", indent, dim("Compiling"), dep_name);
            crate::hex::compile_with_erlang_mk(&dep_path, dep_name, top_project_root)?;
        } else if dep_path.join("rebar.config").exists() {
            eprintln!("{}{} {} (rebar3)...", indent, dim("Compiling"), dep_name);
            crate::hex::compile_with_rebar3(&dep_path, dep_name, top_project_root)?;
        } else if dep_path.join("src").exists()
            && std::fs::read_dir(dep_path.join("src"))
                .map(|entries| {
                    entries
                        .flatten()
                        .any(|e| e.path().extension().is_some_and(|ext| ext == "erl"))
                })
                .unwrap_or(false)
            && !crate::hex::is_compiled(top_project_root, dep_name)
        {
            eprintln!("{}{} {} (erlc)...", indent, dim("Compiling"), dep_name);
            crate::hex::compile_erlang(&dep_path, dep_name, top_project_root)?;
        }

        // Recurse into the dep's own dependencies. top_project_root is
        // unchanged — transitive deps still install flat at the top level.
        install_deps_recursive(top_project_root, &dep_path, lockfile, installing, depth + 1)?;

        installing.remove(&dep_key);
    }

    Ok(())
}

/// Install a Hex dependency and recursively install its transitive deps.
fn install_hex_dep_recursive(
    project_root: &Path,
    dep_name: &str,
    dep_entry: &DepEntry,
    lockfile: &mut Lockfile,
    installing: &mut HashSet<String>,
    indent: &str,
    depth: usize,
) -> Result<(), String> {
    let version = dep_entry
        .version
        .as_deref()
        .ok_or_else(|| format!("Hex dependency '{}' has no version", dep_name))?;

    let dep_key = format!("hex:{}-{}", dep_name, version);
    if !installing.insert(dep_key.clone()) {
        return Err(format!(
            "circular dependency detected: Hex package '{}'",
            dep_name
        ));
    }

    // Skip if already locked at this version
    if let Some(lock_entry) = lockfile.deps.get(dep_name)
        && lock_entry.version.as_deref() == Some(version)
    {
        installing.remove(&dep_key);
        return Ok(());
    }

    // Skip if already compiled and locked at this version
    if crate::hex::is_compiled(project_root, dep_name) {
        // Still need release info to recurse into transitive deps
        let release = crate::hex::prepare_package(project_root, dep_name, version)?;

        lockfile.deps.insert(
            dep_name.to_string(),
            LockEntry::new_hex(
                dep_name.to_string(),
                version.to_string(),
                release.checksum.clone(),
            ),
        );

        // Recursively install transitive deps (they may not be installed yet)
        let child_indent = "  ".repeat(depth + 2);
        for (req_name, req) in &release.requirements {
            if req.optional {
                continue;
            }
            let resolved_version = resolve_hex_requirement(req_name, &req.requirement)?;
            let transitive_entry = DepEntry {
                path: None,
                git: None,
                tag: None,
                branch: None,
                rev: None,
                alias: None,
                version: Some(resolved_version),
            };
            install_hex_dep_recursive(
                project_root,
                req_name,
                &transitive_entry,
                lockfile,
                installing,
                &child_indent,
                depth + 1,
            )?;
        }

        installing.remove(&dep_key);
        return Ok(());
    }

    eprintln!(
        "{}{} {} (hex @ {})...",
        indent,
        dim("Fetching"),
        dep_name,
        version
    );

    // Step 1: Fetch metadata and download/extract (no compilation yet)
    let release = crate::hex::prepare_package(project_root, dep_name, version)?;

    lockfile.deps.insert(
        dep_name.to_string(),
        LockEntry::new_hex(
            dep_name.to_string(),
            version.to_string(),
            release.checksum.clone(),
        ),
    );

    // Step 2: Recursively install transitive deps BEFORE compiling this package
    let child_indent = "  ".repeat(depth + 2);
    for (req_name, req) in &release.requirements {
        if req.optional {
            continue;
        }
        let resolved_version = resolve_hex_requirement(req_name, &req.requirement)?;
        let transitive_entry = DepEntry {
            path: None,
            git: None,
            tag: None,
            branch: None,
            rev: None,
            alias: None,
            version: Some(resolved_version),
        };
        install_hex_dep_recursive(
            project_root,
            req_name,
            &transitive_entry,
            lockfile,
            installing,
            &child_indent,
            depth + 1,
        )?;
    }

    // Step 3: Compile now that all transitive deps are available
    eprintln!("{}{} {}...", indent, dim("Compiling"), dep_name);
    crate::hex::compile_package(project_root, dep_name)?;

    eprintln!("{}{} {} -> {}", indent, cyan("Resolved"), dep_name, version);

    installing.remove(&dep_key);
    Ok(())
}

/// Resolve a Hex version requirement to an exact version.
/// For v1: supports exact versions and basic `~>` requirements.
fn resolve_hex_requirement(name: &str, requirement: &str) -> Result<String, String> {
    let req = requirement.trim();

    // Exact version (e.g., "1.0.1" or "== 1.0.1")
    let exact = req.strip_prefix("== ").unwrap_or(req);
    if !exact.starts_with("~>")
        && !exact.starts_with(">=")
        && !exact.starts_with(">")
        && !exact.starts_with("<=")
        && !exact.starts_with("<")
    {
        return Ok(exact.to_string());
    }

    // ~> requirement: fetch available versions and pick the latest matching one
    if let Some(version_part) = req.strip_prefix("~>") {
        let base = version_part.trim();
        let info = crate::hex::fetch_package_info(name)?;

        let matching = find_latest_compatible(&info.releases, base);
        return matching.ok_or_else(|| {
            format!(
                "no version of '{}' matches requirement '{}'",
                name, requirement
            )
        });
    }

    // For other complex requirements, try to fetch and pick latest
    // This is a simplification for v1
    let info = crate::hex::fetch_package_info(name)?;
    info.releases
        .first()
        .map(|r| r.version.clone())
        .ok_or_else(|| format!("no versions found for '{}'", name))
}

/// Find the latest version compatible with a ~> requirement.
/// `~> 1.0` means >= 1.0.0, < 2.0.0
/// `~> 1.4.2` means >= 1.4.2, < 1.5.0
fn find_latest_compatible(
    releases: &[crate::hex::HexPackageRelease],
    base: &str,
) -> Option<String> {
    let base_parts: Vec<u64> = base.split('.').filter_map(|s| s.parse().ok()).collect();
    if base_parts.is_empty() {
        return None;
    }

    // Build the upper bound: bump the second-to-last segment
    let upper_parts = if base_parts.len() <= 2 {
        // ~> 1.0 -> < 2.0.0
        vec![base_parts[0] + 1, 0, 0]
    } else {
        // ~> 1.4.2 -> < 1.5.0
        let mut upper = base_parts[..base_parts.len() - 1].to_vec();
        if let Some(last) = upper.last_mut() {
            *last += 1;
        }
        upper.push(0);
        upper
    };

    // Releases are returned newest first from the API
    for release in releases {
        let parts: Vec<u64> = release
            .version
            .split('.')
            .filter_map(|s| s.parse().ok())
            .collect();
        if parts.len() < 2 {
            continue;
        }

        // Pad to 3 parts
        let v = [
            parts.first().copied().unwrap_or(0),
            parts.get(1).copied().unwrap_or(0),
            parts.get(2).copied().unwrap_or(0),
        ];
        let b = [
            base_parts.first().copied().unwrap_or(0),
            base_parts.get(1).copied().unwrap_or(0),
            base_parts.get(2).copied().unwrap_or(0),
        ];
        let u = [
            upper_parts.first().copied().unwrap_or(0),
            upper_parts.get(1).copied().unwrap_or(0),
            upper_parts.get(2).copied().unwrap_or(0),
        ];

        if v >= b && v < u {
            return Some(release.version.clone());
        }
    }

    None
}

/// Run `saga install`: fetch all git deps (recursively), resolve refs, write lockfile.
pub fn install_deps(project_root: &Path) -> Result<(), String> {
    let config = ProjectConfig::load(project_root);
    config.validate()?;

    if config.deps.is_none() {
        eprintln!("No dependencies to install.");
        return Ok(());
    }

    let existing_lock = Lockfile::load(project_root);
    let mut lockfile = Lockfile::default();
    let mut installing = HashSet::new();

    install_deps_recursive(
        project_root,
        project_root,
        &mut lockfile,
        &mut installing,
        0,
    )?;

    // Report updates compared to previous lockfile
    if let Some(existing) = &existing_lock {
        for (name, new_entry) in &lockfile.deps {
            if let Some(old_entry) = existing.deps.get(name) {
                // Compare git commits
                if let (Some(old_commit), Some(new_commit)) = (&old_entry.commit, &new_entry.commit)
                    && old_commit != new_commit
                {
                    eprintln!(
                        "  {} {} ({} -> {})",
                        cyan("Updated"),
                        name,
                        &old_commit[..old_commit.len().min(12)],
                        &new_commit[..new_commit.len().min(12)]
                    );
                }
                // Compare hex versions
                if let (Some(old_ver), Some(new_ver)) = (&old_entry.version, &new_entry.version)
                    && old_ver != new_ver
                {
                    eprintln!(
                        "  {} {} ({} -> {})",
                        cyan("Updated"),
                        name,
                        old_ver,
                        new_ver
                    );
                }
            }
        }
    }

    if !lockfile.deps.is_empty() {
        lockfile.save(project_root)?;
        eprintln!("  {} saga.lock", green("Wrote"));
    }

    Ok(())
}

// --- Resolve deps into the checker's module map ---

/// Recursively resolve dependencies and collect their exposed modules.
///
/// Git deps are resolved flat under `top_project_root/deps/`. `config_dir` is
/// the directory of the current project.toml being walked — used to resolve
/// path deps relative to the file that declared them.
fn resolve_deps_recursive(
    top_project_root: &Path,
    config_dir: &Path,
    deps: &HashMap<String, DepEntry>,
    lockfile: Option<&Lockfile>,
    dep_modules: &mut typechecker::ModuleMap,
    resolving: &mut HashSet<String>,
    depth: usize,
) -> Result<(), String> {
    let indent = "  ".repeat(depth + 1);

    for (dep_name, dep_entry) in deps {
        // Skip Hex deps — they're opaque (no typechecking, just beam files)
        if dep_entry.is_hex() {
            continue;
        }

        let dep_path =
            resolve_dep_to_path(dep_name, dep_entry, config_dir, top_project_root, lockfile)?;

        // Cycle detection
        let dep_key = dep_path.to_string_lossy().to_string();
        if !resolving.insert(dep_key.clone()) {
            return Err(format!(
                "circular dependency detected: '{}' at '{}'",
                dep_name,
                dep_path.display()
            ));
        }

        eprintln!(
            "{}{} dependency '{}'...",
            indent,
            dim("Resolving"),
            dep_name
        );

        let dep_config = ProjectConfig::load(&dep_path);
        let lib = dep_config.library.ok_or_else(|| {
            format!(
                "dependency '{}' at '{}' has no [library] section in project.toml",
                dep_name,
                dep_path.display()
            )
        })?;

        // Recurse into this dep's own dependencies first
        if let Some(transitive_deps) = &dep_config.deps {
            resolve_deps_recursive(
                top_project_root,
                &dep_path,
                transitive_deps,
                lockfile,
                dep_modules,
                resolving,
                depth + 1,
            )?;
        }

        // Now scan and collect this dep's exposed modules
        let dep_map = typechecker::scan_project_modules(&dep_path)
            .map_err(|e| format!("scanning dependency '{}': {}", dep_name, e))?;

        for exposed in &lib.expose {
            let file_path = dep_map
                .get(exposed)
                .ok_or_else(|| {
                    format!(
                        "dependency '{}' exposes module '{}' but it was not found",
                        dep_name, exposed
                    )
                })?
                .clone();

            let mapped_name = if let Some(alias) = &dep_entry.alias {
                if exposed == &lib.module {
                    alias.clone()
                } else if let Some(suffix) = exposed.strip_prefix(&format!("{}.", lib.module)) {
                    format!("{}.{}", alias, suffix)
                } else {
                    exposed.clone()
                }
            } else {
                exposed.clone()
            };

            if let Some(existing) = dep_modules.get(&mapped_name) {
                // Same file path = same module from a shared transitive dep, not a collision
                if existing != &file_path {
                    return Err(format!(
                        "module name collision '{}' between dependency '{}' and another dependency ({}). \
                         Hint: use `as` in project.toml to alias one of the dependencies",
                        mapped_name,
                        dep_name,
                        existing.display()
                    ));
                }
            } else {
                dep_modules.insert(mapped_name, file_path);
            }
        }

        resolving.remove(&dep_key);
    }

    Ok(())
}

/// Resolve dependencies and merge their modules into the checker's module map.
pub fn resolve_deps(
    checker: &mut typechecker::Checker,
    project_root: &Path,
    deps: &HashMap<String, DepEntry>,
) -> Result<(), String> {
    let mut dep_modules = typechecker::ModuleMap::new();
    let lockfile = Lockfile::load(project_root);
    let mut resolving = HashSet::new();

    resolve_deps_recursive(
        project_root,
        project_root,
        deps,
        lockfile.as_ref(),
        &mut dep_modules,
        &mut resolving,
        0,
    )?;

    if !dep_modules.is_empty() {
        let module_names: Vec<&str> = dep_modules.keys().map(|s| s.as_str()).collect();
        eprintln!(
            "  {} {} dependency module(s): {}",
            cyan("Resolved"),
            module_names.len(),
            module_names.join(", ")
        );
        let mut map = checker.module_map().cloned().unwrap_or_default();
        for (name, path) in dep_modules {
            if let Some(existing) = map.get(&name) {
                return Err(format!(
                    "dependency module '{}' conflicts with local module at {}. \
                     Hint: use `as` in project.toml to alias the dependency",
                    name,
                    existing.display()
                ));
            }
            map.insert(name, path);
        }
        checker.set_module_map(map);
    }

    Ok(())
}

/// Collect the root paths of all direct dependencies (non-Hex only).
pub fn dep_root_paths(project_root: &Path, deps: &HashMap<String, DepEntry>) -> Vec<PathBuf> {
    let lockfile = Lockfile::load(project_root);
    let mut roots = Vec::new();
    for (dep_name, dep_entry) in deps {
        if dep_entry.is_hex() {
            continue;
        }
        if let Ok(path) = resolve_dep_to_path(
            dep_name,
            dep_entry,
            project_root,
            project_root,
            lockfile.as_ref(),
        ) {
            roots.push(path);
        }
    }
    roots
}

/// Collect ebin directories for all dependencies.
/// Scans deps/ for Hex packages and git deps (installed flat under deps/), and
/// resolves direct path deps separately (they live outside deps/).
pub fn extra_ebin_dirs(
    project_root: &Path,
    deps: Option<&HashMap<String, DepEntry>>,
) -> Vec<PathBuf> {
    let mut dirs = Vec::new();

    // Scan deps/ — every hex and git dep (direct or transitive) lives here.
    let deps_dir = project_root.join("deps");
    if deps_dir.exists()
        && let Ok(entries) = std::fs::read_dir(&deps_dir)
    {
        for entry in entries.flatten() {
            let ebin = entry.path().join("ebin");
            if ebin.exists() {
                dirs.push(ebin);
            }
        }
    }

    // Path deps: sources live wherever the user pointed, so resolve them
    // relative to the top-level project_root. Only direct path deps are
    // handled — transitive path deps aren't currently supported.
    if let Some(deps) = deps {
        let lockfile = Lockfile::load(project_root);
        for (dep_name, dep_entry) in deps {
            if dep_entry.is_hex() || dep_entry.git.is_some() {
                continue; // already in deps/
            }
            if let Ok(dep_path) = resolve_dep_to_path(
                dep_name,
                dep_entry,
                project_root,
                project_root,
                lockfile.as_ref(),
            ) {
                let ebin = dep_path.join("ebin");
                if ebin.exists() {
                    dirs.push(ebin);
                }
            }
        }
    }

    dirs
}
