use serde::Deserialize;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

use crate::typechecker;

/// Parsed project.toml configuration.
#[derive(Debug, Deserialize, Default)]
pub struct ProjectConfig {
    #[serde(default)]
    pub project: ProjectSection,
    #[serde(default)]
    pub library: Option<LibrarySection>,
    #[serde(default)]
    pub bin: Option<BinSection>,
    #[serde(default)]
    pub deps: Option<HashMap<String, DepEntry>>,
}

#[derive(Debug, Deserialize, Default)]
#[allow(dead_code)]
pub struct ProjectSection {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub tests_dir: Option<String>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct LibrarySection {
    pub module: String,
    pub expose: Vec<String>,
}

#[derive(Debug, Deserialize, Clone, Default)]
pub struct BinSection {
    #[serde(default)]
    pub main: Option<String>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct DepEntry {
    /// Local path dependency.
    #[serde(default)]
    pub path: Option<String>,
    /// Git repository URL.
    #[serde(default)]
    pub git: Option<String>,
    /// Git tag to checkout.
    #[serde(default)]
    pub tag: Option<String>,
    /// Git branch to checkout.
    #[serde(default)]
    pub branch: Option<String>,
    /// Exact git commit hash to checkout.
    #[serde(default)]
    pub rev: Option<String>,
    /// Module name alias for the dependency.
    #[serde(rename = "as")]
    pub alias: Option<String>,
}

/// Resolved lockfile entry for a git dependency.
#[derive(Debug, Deserialize, serde::Serialize, Clone)]
pub struct LockEntry {
    pub git: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    pub commit: String,
}

/// Parsed dylang.lock file.
#[derive(Debug, Deserialize, serde::Serialize, Default)]
pub struct Lockfile {
    #[serde(default)]
    pub deps: HashMap<String, LockEntry>,
}

impl Lockfile {
    pub fn load(project_root: &Path) -> Option<Self> {
        let path = project_root.join("dylang.lock");
        let contents = std::fs::read_to_string(&path).ok()?;
        toml::from_str(&contents).ok()
    }

    pub fn save(&self, project_root: &Path) -> Result<(), String> {
        let path = project_root.join("dylang.lock");
        let contents = toml::to_string_pretty(self)
            .map_err(|e| format!("failed to serialize lockfile: {}", e))?;
        let header = "# This file is auto-generated by dylang. Do not edit.\n\n";
        std::fs::write(&path, format!("{}{}", header, contents))
            .map_err(|e| format!("failed to write dylang.lock: {}", e))
    }
}

impl ProjectConfig {
    pub fn load(project_root: &Path) -> Self {
        let path = project_root.join("project.toml");
        match std::fs::read_to_string(&path) {
            Ok(contents) => toml::from_str(&contents).unwrap_or_else(|e| {
                eprintln!("Warning: failed to parse project.toml: {}", e);
                ProjectConfig::default()
            }),
            Err(_) => ProjectConfig::default(),
        }
    }

    pub fn tests_dir(&self) -> &str {
        self.project.tests_dir.as_deref().unwrap_or("tests")
    }

    /// The main entry point file. Defaults to "Main.dy".
    pub fn main_file(&self) -> &str {
        self.bin
            .as_ref()
            .and_then(|b| b.main.as_deref())
            .unwrap_or("Main.dy")
    }

    /// Whether this project can be run (has a binary entry point).
    pub fn is_bin(&self) -> bool {
        // Backward compat: if no [library] or [bin] section, treat as bin
        if self.library.is_none() && self.bin.is_none() {
            return true;
        }
        self.bin.is_some()
    }

    /// Whether this project is a library.
    #[allow(dead_code)]
    pub fn is_library(&self) -> bool {
        self.library.is_some()
    }

    /// Validate the config, returning errors if any.
    pub fn validate(&self) -> Result<(), String> {
        if let Some(lib) = &self.library {
            for exposed in &lib.expose {
                if exposed != &lib.module && !exposed.starts_with(&format!("{}.", lib.module)) {
                    return Err(format!(
                        "exposed module '{}' must be prefixed by library module '{}'",
                        exposed, lib.module
                    ));
                }
            }
        }

        if let Some(deps) = &self.deps {
            for (name, dep) in deps {
                if dep.path.is_none() && dep.git.is_none() {
                    return Err(format!(
                        "dependency '{}' must have either 'path' or 'git'",
                        name
                    ));
                }
                if dep.path.is_some() && dep.git.is_some() {
                    return Err(format!(
                        "dependency '{}' cannot have both 'path' and 'git'",
                        name
                    ));
                }
                if let Some(path) = &dep.path {
                    let dep_path = Path::new(path);
                    if !dep_path.exists() {
                        return Err(format!(
                            "dependency '{}' path '{}' does not exist",
                            name, path
                        ));
                    }
                    if !dep_path.join("project.toml").exists() {
                        return Err(format!(
                            "dependency '{}' at '{}' has no project.toml",
                            name, path
                        ));
                    }
                }
                if dep.git.is_some() {
                    let ref_count = [&dep.tag, &dep.branch, &dep.rev]
                        .iter()
                        .filter(|r| r.is_some())
                        .count();
                    if ref_count > 1 {
                        return Err(format!(
                            "dependency '{}' can only specify one of 'tag', 'branch', or 'rev'",
                            name
                        ));
                    }
                }
            }
        }

        Ok(())
    }
}

// --- Git dependency caching ---

/// Get the global cache directory for git dependencies.
fn cache_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home)
        .join(".dylang")
        .join("cache")
        .join("git")
}

/// Hash a git URL to a short directory name.
fn url_hash(url: &str) -> String {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    url.hash(&mut hasher);
    let hash = hasher.finish();
    let name = url
        .trim_end_matches('/')
        .rsplit('/')
        .next()
        .unwrap_or("dep")
        .trim_end_matches(".git");
    format!("{}-{:016x}", name, hash)
}

/// Ensure a bare clone of the repo exists in the cache. Returns the path to the bare repo.
/// If `needed_commit` is provided and already exists in the repo, skip fetching.
fn ensure_bare_clone(url: &str, needed_commit: Option<&str>) -> Result<PathBuf, String> {
    let dir = cache_dir().join(url_hash(url));
    let repo_dir = dir.join("repo");

    if repo_dir.exists() {
        // If we already have the commit we need, skip the network fetch
        if let Some(commit) = needed_commit {
            let output = std::process::Command::new("git")
                .args(["cat-file", "-t", commit])
                .current_dir(&repo_dir)
                .output()
                .map_err(|e| format!("failed to run git cat-file: {}", e))?;
            if output.status.success() {
                return Ok(repo_dir);
            }
        }

        let status = std::process::Command::new("git")
            .args(["fetch", "--all", "--tags", "--quiet"])
            .current_dir(&repo_dir)
            .status()
            .map_err(|e| format!("failed to run git fetch: {}", e))?;
        if !status.success() {
            return Err(format!("git fetch failed for {}", url));
        }
    } else {
        std::fs::create_dir_all(&dir).map_err(|e| format!("failed to create cache dir: {}", e))?;
        let status = std::process::Command::new("git")
            .args(["clone", "--bare", "--quiet", url])
            .arg(&repo_dir)
            .status()
            .map_err(|e| format!("failed to run git clone: {}", e))?;
        if !status.success() {
            return Err(format!("git clone failed for {}", url));
        }
    }

    Ok(repo_dir)
}

/// Resolve a git ref (tag, branch, or rev) to a concrete commit hash.
fn resolve_ref(bare_repo: &Path, dep: &DepEntry) -> Result<String, String> {
    let ref_spec = if let Some(tag) = &dep.tag {
        format!("refs/tags/{}", tag)
    } else if let Some(branch) = &dep.branch {
        format!("refs/heads/{}", branch)
    } else if let Some(rev) = &dep.rev {
        rev.clone()
    } else {
        "HEAD".to_string()
    };

    let output = std::process::Command::new("git")
        .args(["rev-parse", &ref_spec])
        .current_dir(bare_repo)
        .output()
        .map_err(|e| format!("failed to run git rev-parse: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "failed to resolve ref '{}': {}",
            ref_spec,
            stderr.trim()
        ));
    }

    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

/// Ensure a working copy at a specific commit exists. Returns the path to the checkout.
fn ensure_checkout(bare_repo: &Path, commit: &str) -> Result<PathBuf, String> {
    let checkout_dir = bare_repo.parent().unwrap().join(commit);

    if checkout_dir.exists() {
        return Ok(checkout_dir);
    }

    std::fs::create_dir_all(&checkout_dir)
        .map_err(|e| format!("failed to create checkout dir: {}", e))?;

    let status = std::process::Command::new("git")
        .args(["clone", "--quiet"])
        .arg(bare_repo)
        .arg(&checkout_dir)
        .status()
        .map_err(|e| format!("failed to clone from cache: {}", e))?;
    if !status.success() {
        let _ = std::fs::remove_dir_all(&checkout_dir);
        return Err("git clone from cache failed".to_string());
    }

    let status = std::process::Command::new("git")
        .args(["checkout", "--quiet", commit])
        .current_dir(&checkout_dir)
        .status()
        .map_err(|e| format!("failed to checkout {}: {}", commit, e))?;
    if !status.success() {
        let _ = std::fs::remove_dir_all(&checkout_dir);
        return Err(format!("git checkout failed for commit {}", commit));
    }

    Ok(checkout_dir)
}

/// Resolve a git dependency to a local path, fetching/caching as needed.
/// Returns (checkout_path, resolved_commit).
pub fn resolve_git_dep(
    dep_name: &str,
    dep: &DepEntry,
    locked_commit: Option<&str>,
) -> Result<(PathBuf, String), String> {
    let url = dep
        .git
        .as_ref()
        .ok_or_else(|| format!("dependency '{}' has no git URL", dep_name))?;

    let bare_repo = ensure_bare_clone(url, locked_commit)?;

    let commit = if let Some(locked) = locked_commit {
        locked.to_string()
    } else {
        resolve_ref(&bare_repo, dep)?
    };

    let checkout = ensure_checkout(&bare_repo, &commit)?;

    Ok((checkout, commit))
}

// --- Resolve a dep entry to a local directory path ---

/// Resolve a single dependency to a local filesystem path.
/// For path deps, joins with the parent directory. For git deps, uses the cache.
fn resolve_dep_to_path(
    dep_name: &str,
    dep_entry: &DepEntry,
    parent_dir: &Path,
    lockfile: Option<&Lockfile>,
) -> Result<PathBuf, String> {
    if let Some(path) = &dep_entry.path {
        let p = parent_dir.join(path);
        p.canonicalize()
            .map_err(|e| format!("dependency '{}' path '{}': {}", dep_name, path, e))
    } else if dep_entry.git.is_some() {
        let locked_commit = lockfile
            .and_then(|lf| lf.deps.get(dep_name))
            .map(|entry| entry.commit.as_str());

        if locked_commit.is_none() {
            return Err(format!(
                "git dependency '{}' is not installed. Run `dylang install` first.",
                dep_name
            ));
        }

        let (checkout_path, _) = resolve_git_dep(dep_name, dep_entry, locked_commit)?;
        Ok(checkout_path)
    } else {
        Err(format!("dependency '{}' has no 'path' or 'git'", dep_name))
    }
}

// --- Install (fetch + lockfile) ---

/// Recursively fetch all git deps and collect lock entries.
fn install_deps_recursive(
    project_root: &Path,
    lockfile: &mut Lockfile,
    installing: &mut HashSet<String>,
    depth: usize,
) -> Result<(), String> {
    let config = ProjectConfig::load(project_root);

    let deps = match &config.deps {
        Some(deps) => deps.clone(),
        None => return Ok(()),
    };

    let indent = "  ".repeat(depth + 1);

    for (dep_name, dep_entry) in &deps {
        // Cycle detection
        let dep_key = if let Some(url) = &dep_entry.git {
            url.clone()
        } else if let Some(path) = &dep_entry.path {
            project_root
                .join(path)
                .canonicalize()
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_else(|_| path.clone())
        } else {
            continue;
        };

        if !installing.insert(dep_key.clone()) {
            return Err(format!(
                "circular dependency detected: '{}' depends on itself (directly or transitively)",
                dep_name
            ));
        }

        let dep_path = if let Some(url) = &dep_entry.git {
            let ref_label = dep_entry
                .tag
                .as_deref()
                .or(dep_entry.branch.as_deref())
                .or(dep_entry.rev.as_deref())
                .unwrap_or("HEAD");

            eprintln!(
                "{}Fetching {} ({} @ {})...",
                indent, dep_name, url, ref_label
            );

            let (checkout_path, commit) = resolve_git_dep(dep_name, dep_entry, None)?;

            let dep_config = ProjectConfig::load(&checkout_path);
            if dep_config.library.is_none() {
                return Err(format!(
                    "git dependency '{}' has no [library] section in project.toml",
                    dep_name
                ));
            }

            let short_commit = &commit[..commit.len().min(12)];
            eprintln!("{}Resolved {} -> {}", indent, dep_name, short_commit);

            lockfile.deps.insert(
                dep_name.clone(),
                LockEntry {
                    git: url.clone(),
                    r#ref: dep_entry.tag.clone().or(dep_entry.branch.clone()),
                    commit,
                },
            );

            checkout_path
        } else if let Some(path) = &dep_entry.path {
            let p = project_root.join(path);
            p.canonicalize()
                .map_err(|e| format!("dependency '{}' path '{}': {}", dep_name, path, e))?
        } else {
            continue;
        };

        // Recurse into the dep's own dependencies
        install_deps_recursive(&dep_path, lockfile, installing, depth + 1)?;

        installing.remove(&dep_key);
    }

    Ok(())
}

/// Run `dylang install`: fetch all git deps (recursively), resolve refs, write lockfile.
pub fn install_deps(project_root: &Path) -> Result<(), String> {
    let config = ProjectConfig::load(project_root);
    config.validate()?;

    if config.deps.is_none() {
        eprintln!("No dependencies to install.");
        return Ok(());
    }

    let existing_lock = Lockfile::load(project_root);
    let mut lockfile = Lockfile::default();
    let mut installing = HashSet::new();

    install_deps_recursive(project_root, &mut lockfile, &mut installing, 0)?;

    // Report updates compared to previous lockfile
    if let Some(existing) = &existing_lock {
        for (name, new_entry) in &lockfile.deps {
            if let Some(old_entry) = existing.deps.get(name)
                && old_entry.commit != new_entry.commit
            {
                eprintln!(
                    "  Updated {} ({} -> {})",
                    name,
                    &old_entry.commit[..old_entry.commit.len().min(12)],
                    &new_entry.commit[..new_entry.commit.len().min(12)]
                );
            }
        }
    }

    if !lockfile.deps.is_empty() {
        lockfile.save(project_root)?;
        eprintln!("  Wrote dylang.lock");
    }

    Ok(())
}

// --- Resolve deps into the checker's module map ---

/// Recursively resolve dependencies and collect their exposed modules.
fn resolve_deps_recursive(
    parent_dir: &Path,
    deps: &HashMap<String, DepEntry>,
    lockfile: Option<&Lockfile>,
    dep_modules: &mut typechecker::ModuleMap,
    resolving: &mut HashSet<String>,
    depth: usize,
) -> Result<(), String> {
    let indent = "  ".repeat(depth + 1);

    for (dep_name, dep_entry) in deps {
        let dep_path = resolve_dep_to_path(dep_name, dep_entry, parent_dir, lockfile)?;

        // Cycle detection
        let dep_key = dep_path.to_string_lossy().to_string();
        if !resolving.insert(dep_key.clone()) {
            return Err(format!(
                "circular dependency detected: '{}' at '{}'",
                dep_name,
                dep_path.display()
            ));
        }

        eprintln!("{}Resolving dependency '{}'...", indent, dep_name);

        let dep_config = ProjectConfig::load(&dep_path);
        let lib = dep_config.library.ok_or_else(|| {
            format!(
                "dependency '{}' at '{}' has no [library] section in project.toml",
                dep_name,
                dep_path.display()
            )
        })?;

        // Recurse into this dep's own dependencies first
        if let Some(transitive_deps) = &dep_config.deps {
            resolve_deps_recursive(
                &dep_path,
                transitive_deps,
                lockfile,
                dep_modules,
                resolving,
                depth + 1,
            )?;
        }

        // Now scan and collect this dep's exposed modules
        let dep_map = typechecker::scan_project_modules(&dep_path)
            .map_err(|e| format!("scanning dependency '{}': {}", dep_name, e))?;

        for exposed in &lib.expose {
            let file_path = dep_map
                .get(exposed)
                .ok_or_else(|| {
                    format!(
                        "dependency '{}' exposes module '{}' but it was not found",
                        dep_name, exposed
                    )
                })?
                .clone();

            let mapped_name = if let Some(alias) = &dep_entry.alias {
                if exposed == &lib.module {
                    alias.clone()
                } else if let Some(suffix) = exposed.strip_prefix(&format!("{}.", lib.module)) {
                    format!("{}.{}", alias, suffix)
                } else {
                    exposed.clone()
                }
            } else {
                exposed.clone()
            };

            if let Some(existing) = dep_modules.get(&mapped_name) {
                // Same file path = same module from a shared transitive dep, not a collision
                if existing != &file_path {
                    return Err(format!(
                        "module name collision '{}' between dependency '{}' and another dependency ({}). \
                         Hint: use `as` in project.toml to alias one of the dependencies",
                        mapped_name,
                        dep_name,
                        existing.display()
                    ));
                }
            } else {
                dep_modules.insert(mapped_name, file_path);
            }
        }

        resolving.remove(&dep_key);
    }

    Ok(())
}

/// Resolve dependencies and merge their modules into the checker's module map.
pub fn resolve_deps(
    checker: &mut typechecker::Checker,
    project_root: &Path,
    deps: &HashMap<String, DepEntry>,
) -> Result<(), String> {
    let mut dep_modules = typechecker::ModuleMap::new();
    let lockfile = Lockfile::load(project_root);
    let mut resolving = HashSet::new();

    resolve_deps_recursive(
        project_root,
        deps,
        lockfile.as_ref(),
        &mut dep_modules,
        &mut resolving,
        0,
    )?;

    if !dep_modules.is_empty() {
        let module_names: Vec<&str> = dep_modules.keys().map(|s| s.as_str()).collect();
        eprintln!(
            "  Resolved {} dependency module(s): {}",
            module_names.len(),
            module_names.join(", ")
        );
        let mut map = checker.module_map().cloned().unwrap_or_default();
        for (name, path) in dep_modules {
            if let Some(existing) = map.get(&name) {
                return Err(format!(
                    "dependency module '{}' conflicts with local module at {}. \
                     Hint: use `as` in project.toml to alias the dependency",
                    name,
                    existing.display()
                ));
            }
            map.insert(name, path);
        }
        checker.set_module_map(map);
    }

    Ok(())
}

/// Collect the root paths of all direct dependencies.
pub fn dep_root_paths(
    project_root: &Path,
    deps: &HashMap<String, DepEntry>,
) -> Vec<PathBuf> {
    let lockfile = Lockfile::load(project_root);
    let mut roots = Vec::new();
    for (dep_name, dep_entry) in deps {
        if let Ok(path) = resolve_dep_to_path(dep_name, dep_entry, project_root, lockfile.as_ref())
        {
            roots.push(path);
        }
    }
    roots
}
